### ISSUE TITLE
Rename functions to lower case

### ISSUE THREAD

**Issue by pdeffebach** [doganmehmet/PortfolioAnalytics.jl#6]
Congratulations on your package!

One thing I noticed looking at your readme is that you use upper case for your function names. This is syntactically allowed, but is at odds with the rest of the Julia ecosystem. If you look at other packages, say DataFrames.jl, StatsBase.jl, and GLM.jl, you will notice that *methods* are all lower-case with underscores, while *constructors* are in UpperCamelCase. 

See a style guide [here](https://github.com/invenia/BlueStyle#synopsis). 

Would you consider renaming your functions to be more in line with the rest of the ecosystem?

**Comment by doganmehmet** [comment]
Thanks very much for the advice. I can definitely consider if it will be beneficial for the wider Julia community.

By the way I would be happy to hear suggestions in particularly for the following functions:
- Return( )
- VaR( )
- StdDev( )

**Comment by pdeffebach** [comment]
I would rename these functions entirely. `portfolio_return`, `portfolio_var`, `portfolio_stddev`. 

Only keep them as `return`, `var`, and `stddev` if you are are writing your own type to use them with. Since these functions apply to `TSFrame`s, you don't own the type and can't do that.

**Comment by doganmehmet** [comment]
Thank you for advice but these names are confusing for users. That's the reason I wanted to keep them with capital letters.
Return is not for portfolio. 
VaR is short for Value at Risk and name convention is industry standard - and calculation is not only for portfolio. Lowercase "var" is confusing as var is used for variance. 
StdDev is again not only for portfolio. Portfolio std is different from single stock std. 

At the moment I changed them to lowercase in dev version for everything except:
Return
VaR

I will think of alternatives, but the reason is well understood i believe.

**Comment by pdeffebach** [comment]
Why not just `value_at_risk`, then? It's not that long and it increases clarity. 

What does `Return` apply to, then?

**Comment by doganmehmet** [comment]
If it is really important why not. 
valueatrisk or value_at_risk is fine i believe.

Return is basically percentage change. It calculates either simple return or log return. The best candidate for me:
price_change

**Comment by doganmehmet** [comment]
Thanks for advice. Done. 
https://github.com/JuliaRegistries/General/pull/78837
